services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: learninglog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./go/api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/learninglog?sslmode=disable
    depends_on:
      - db

volumes:
  pgdata:
